apiVersion: v1
kind: Service
metadata:
  labels:
    service.name: api-gateway
  name: api-gateway
spec:
  type: NodePort # Using this to connect loadBalancer to in CSCloud
  ports:
    - name: "api-gateway-port"
      port: 8888
      targetPort: 8080
  selector:
    deployment.name: api-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment.name: api-gateway
  template:
    metadata:
      labels:
        deployment.name: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: api-gateway:latest
        env:
        - name: PORT
          value: "8080"
        - name: NODE_PORT
          value: "3000"
        - name: PROFILE_SERVICE
          value: http://profile:8889/graphql
        - name: AUTH_SERVICE
          value: http://auth:8890/graphql
        - name: FEED_SERVICE
          value: http://feed:8891/graphql
        - name: ORIGIN
          value: http://localhost
        ports:
          - containerPort: 8080
