apiVersion: v1
kind: Service
metadata:
  labels:
    service.name: feed
  name: feed
spec:
  type: NodePort # Using this to connect loadBalancer to in CSCloud
  ports:
    - name: "feed-port"
      port: 8891
      targetPort: 8080
  selector:
    deployment.name: feed
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment.name: feed
  template:
    metadata:
      labels:
        deployment.name: feed
    spec:
      containers:
      - name: feed
        image: feed:latest
        env:
        - name: PORT
          value: "8080"
        - name: NODE_PORT
          value: "3000"
        - name: USER_READ_SERVICE
          value: "http://user-read:8895/api/usersread"
        - name: LIT_READ_SERVICE
          value: "http://lit-read:8892/api/litsread"
        - name: RABBITMQ_CONNECTION_STRING
          value: "amqp://admin:password@sphynx-queue-rabbitmq:5672?heartbeat=10"
        - name: REFRESH_TOKEN_SECRET
          value: "alocalrefreshsecret"
        - name: ACCESS_TOKEN_SECRET
          value: "alocalaccesssecret"
        ports:
          - containerPort: 8080
