apiVersion: v1
kind: Service
metadata:
  labels:
    service.name: user-write
  name: user-write
spec:
  type: NodePort # Using this to connect loadBalancer to in CSCloud
  ports:
    - name: "user-write-port"
      port: 8894
      targetPort: 8080
  selector:
    deployment.name: user-write
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-write
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment.name: user-write
  template:
    metadata:
      labels:
        deployment.name: user-write
    spec:
      containers:
      - name: user-write
        image: user-write:latest
        env:
        - name: PORT
          value: "8080"
        - name: NODE_PORT
          value: "3000"
        - name: BASE_URL
          value: /api/userswrite
        - name: DATABASE_URL
          value: mysql://root:localdevpassword@sphynx-users-mysql-primary:3306/my_database
        - name: ACCESS_TOKEN_SECRET
          value: "alocalaccesssecret"
        ports:
          - containerPort: 8080
