apiVersion: v1
kind: Service
metadata:
  labels:
    service.name: feed
  name: feed
spec:
  type: NodePort # Using this to connect loadBalancer to in CSCloud
  ports:
    - name: "feed-port"
      port: 8891
      targetPort: 8080
  selector:
    deployment.name: feed
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment.name: feed
  template:
    metadata:
      labels:
        deployment.name: feed
    spec:
      containers:
      - name: feed
        image: gitlab.lnu.se:5050/2dv013/student/team-6-sphynx/litter/feed:latest
        env:
        - name: PORT
          value: "8080"
        - name: NODE_PORT
          value: "3000"
        - name: USER_READ_SERVICE
          value: "http://user-read:8895/api"
        - name: LIT_READ_SERVICE
          value: "http://lit-read:8892/api"
        - name: REFRESH_TOKEN_SECRET
          valueFrom: 
            secretKeyRef:
              name: jwt-secret
              key: refresh-token
        - name: ACCESS_TOKEN_SECRET
          valueFrom: 
            secretKeyRef:
              name: jwt-secret
              key: access-token
        - name: RABBITMQ_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: sphynx-lits-mysql
              key: mysql-root-password
        - name: RABBITMQ_CONNECTION_STRING
          value: "amqp://user:$(RABBITMQ_PASSWORD)@sphynx-queue-rabbitmq:5672?heartbeat=10"
        ports:
          - containerPort: 8080
      imagePullSecrets:
      - name: regcred # Secret set as a secret in the cluster
