apiVersion: v1
kind: Service
metadata:
  labels:
    service.name: user-read
  name: user-read
spec:
  type: NodePort # Using this to connect loadBalancer to in CSCloud
  ports:
    - name: "user-read-port"
      port: 8895
      targetPort: 8080
  selector:
    deployment.name: user-read
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-read
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment.name: user-read
  template:
    metadata:
      labels:
        deployment.name: user-read
    spec:
      containers:
      - name: user-read
        image: gitlab.lnu.se:5050/2dv013/student/team-6-sphynx/litter/user-read:latest
        env:
        - name: PORT
          value: "8080"
        - name: NODE_PORT
          value: "3000"
        - name: BASE_URL
          value: /api
        - name: MYSQL_USERNAME
          value: root
        - name: MYSQL_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: sphynx-users-mysql
              key: mysql-root-password
        - name: DATABASE_URL
          value: mysql://$(MYSQL_USERNAME):$(MYSQL_PASSWORD)@sphynx-users-mysql-secondary:3306/my_database
        ports:
          - containerPort: 8080
      imagePullSecrets:
      - name: regcred # Secret set as a secret in the cluster
