# First build the React App
FROM node:19-bullseye-slim AS builder
WORKDIR /app
COPY package*.json .
RUN npm i
COPY . .
RUN npm run build

# Then build the NGINX instance serving static assets
FROM nginx:1.23.2-alpine AS nginx
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx.conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]